name: ROS2 CI

on:
  pull_request:
    branches:
      - 'develop'
      - 'main'

jobs:
  test_environment:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - dashing
          - foxy
          - rolling
        include:
          # Dashing Diademata (May 2019 - May 2021)
          - docker_image: ubuntu:bionic
            ros_distribution: dashing
            ros_version: 2
          # Foxy Fitzroy (June 2020 - May 2023)
          - docker_image: ubuntu:focal
            ros_distribution: foxy
            ros_version: 2
          # Rolling Ridley  (June 2020 - Present)
          - docker_image: ubuntu:focal
            ros_distribution: rolling
            ros_version: 2
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: setup directories
        run: mkdir -p ros_ws/src
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ros_ws/src
      - name: setup ROS environment
        uses: ros-tooling/setup-ros@master
        with:
          install-connext: false
          use-ros2-testing: false
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - uses: ros-tooling/action-ros-lint@master
        with:
          linter: flake8
          package-name: bno055
          distribution: ${{ matrix.ros_distribution }}
      - name: install dependencies
        run: "pip3 install -r ros_ws/src/requirements.txt"
      - name: build and test
        uses: ros-tooling/action-ros-ci@master
        with:
          package-name: bno055
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: ""
